"""
solver_optimizador: Suite modular de optimizacion matematica.
Modulo base para LP monoobjetivo y biobjetivo por ponderaciones.
"""

from .lp_models import (
    Sense,
    Operator,
    LinearObjective,
    LinearConstraint,
    LPProblem,
    BiobjectiveProblem,
    SolverStatus,
    ConstraintResult,
    LPSolution,
    MultiobjectiveSolution,
    is_finite_number,
)
from .lp_solver import solve_lp
from .multiobjective import (
    generate_weight_combinations,
    normalize_objective_value,
    solve_biobjective_weighted,
    solve_lexicographic_extreme,
)
from .signature import build_model_signature
from .interpretation import interpret_mono_solution, interpret_biobjective_solution
from .model_io import (
    serialize_model,
    deserialize_model,
    validate_model_dict,
    normalize_constraints,
    is_empty_constraint_row,
    sanitize_filename,
    SCHEMA_VERSION,
)
from .problem_builder import (
    build_lp_problem_from_state,
    build_biobjective_problem_from_state,
)
from .constraint_import import (
    RESERVED_VARIABLE_NAMES,
    ConstraintImportResult,
    ObjectiveImportResult,
    VariableImportResult,
    constraints_to_sparse_csv,
    import_constraint_table,
    list_xlsx_sheets,
    parse_constraint_text,
    parse_objective_text,
    parse_variable_names,
    parse_xlsx_constraints,
    validate_variable_names,
)
from .input_application import (
    apply_constraint_import,
    apply_manual_variable_rename,
    apply_objective_import,
    apply_variable_import,
)
from .indexed_application import (
    IndexedPreviewSynchronizationError,
    apply_indexed_model,
    apply_indexed_preview_if_current,
    mark_indexed_source_stale,
)
from .indexed_compiler import compile_indexed_model
from .indexed_model import (
    INDEXED_SCHEMA_VERSION,
    ConstraintFamilySpec,
    ExpandedIndexedModel,
    IndexedModelSpec,
    IndexedObjectiveSpec,
    IndexedParameterSpec,
    IndexSetSpec,
    ObjectiveTermSpec,
    ScalarParameterSpec,
    VariableFamilySpec,
    build_indexed_spec_signature,
    deserialize_indexed_model_spec,
    is_indexed_preview_current,
    serialize_indexed_model_spec,
)
from .plotting import (
    plot_feasible_region_2d,
    plot_objective_space_2d,
    plot_variable_values,
    plot_constraint_slacks,
    plot_multiobjective_runs,
)

__all__ = [
    "Sense",
    "Operator",
    "LinearObjective",
    "LinearConstraint",
    "LPProblem",
    "BiobjectiveProblem",
    "SolverStatus",
    "ConstraintResult",
    "LPSolution",
    "MultiobjectiveSolution",
    "is_finite_number",
    "build_model_signature",
    "interpret_mono_solution",
    "interpret_biobjective_solution",
    "serialize_model",
    "deserialize_model",
    "validate_model_dict",
    "normalize_constraints",
    "is_empty_constraint_row",
    "sanitize_filename",
    "SCHEMA_VERSION",
    "plot_feasible_region_2d",
    "plot_objective_space_2d",
    "plot_variable_values",
    "plot_constraint_slacks",
    "plot_multiobjective_runs",
    "build_lp_problem_from_state",
    "build_biobjective_problem_from_state",
    "ConstraintImportResult",
    "RESERVED_VARIABLE_NAMES",
    "ObjectiveImportResult",
    "VariableImportResult",
    "constraints_to_sparse_csv",
    "import_constraint_table",
    "list_xlsx_sheets",
    "parse_constraint_text",
    "parse_objective_text",
    "parse_variable_names",
    "parse_xlsx_constraints",
    "validate_variable_names",
    "apply_constraint_import",
    "apply_manual_variable_rename",
    "apply_objective_import",
    "apply_variable_import",
    "INDEXED_SCHEMA_VERSION",
    "IndexSetSpec",
    "ScalarParameterSpec",
    "IndexedParameterSpec",
    "VariableFamilySpec",
    "ObjectiveTermSpec",
    "IndexedObjectiveSpec",
    "ConstraintFamilySpec",
    "IndexedModelSpec",
    "ExpandedIndexedModel",
    "compile_indexed_model",
    "apply_indexed_model",
    "apply_indexed_preview_if_current",
    "IndexedPreviewSynchronizationError",
    "mark_indexed_source_stale",
    "build_indexed_spec_signature",
    "is_indexed_preview_current",
    "serialize_indexed_model_spec",
    "deserialize_indexed_model_spec",
    "solve_lp",
    "solve_biobjective_weighted",
    "solve_lexicographic_extreme",
    "generate_weight_combinations",
    "normalize_objective_value",
]
